---
- name: Insuring openssl is installed and up to date.
  apt:
    name: openssl
    state: latest
    update_cache: true

- name: templating temporary cnf file for adding a SAN to the self-signed cert.
  template:
    src: templates/temp-prefix.cnf.j2
    dest: /tmp/prefix.cnf

- name: Creating directories for certs.
  file:
    path: /data/moloch/etc/certs/{{ node_name }}
    state: directory
    mode: 0755

- name: Generating Self-signed Certs
  shell: |
    openssl genrsa -out {{ cert_path }}.key 4096
    openssl req -new -sha256 -key {{ cert_path }}.key -subj "/C=INT/ST=Crazy/L=Here/O=IceCreamMan/CN={{ node_name }}" -out {{ cert_path }}.csr
    openssl x509 -req -extensions v3_req -days 3650 -in {{ cert_path }}.csr -signkey {{ cert_path }}.key -out {{ cert_path }}.crt -extfile /tmp/prefix.cnf
  args:
    creates: "{{ cert_path }}.key"

- name: cleanup
  file:
    path: /tmp/prefix.cnf
    state: absent
...
