---
# Generate self-signed certs if approved, and pre-exsisting certs do not exsist.
- include_tasks: cert_creation.yml
  when:
    - node_certs_exists.stat.exists == False
    - ( self_sign.user_input|lower == "y" ) or
      ( self_sign == "y" )

- include_tasks: var_templating.yml
  when: ( vars_exists.stat.exists == False ) or
        ( fresh_vars|lower == "y" )
...
